name: _sync

on:
  workflow_call:

jobs:
  sync:
    name: Project labels
    runs-on: ubuntu-latest
    steps:
      - uses: EndBug/label-sync@v2
        with:
          # If you want to use a config file, you can put its path or URL here, multiple files are also allowed (more info in the paragraphs below)
          # as multiple:
          config-file: |
            https://raw.githubusercontent.com/ramizpolic/testing/main/.github/labels.yml

          # If you want to delete any additional label, set this to true
          delete-other-labels: false

          # If you want the action just to show you the preview of the changes, without actually editing the labels, set this to true
          dry-run: false

          # You can change the token used to change the labels, this is the default one
          token: ${{ secrets.GITHUB_TOKEN }}
