name: pr-sync

on:
  pull_request_target:
    types:
      - opened
      - edited
      - reopened
      - synchronize

jobs:
  check:
    uses: ./.github/workflows/_pr_check.yml
    permissions:
      pull-requests: write

  sync:
    uses: ./.github/workflows/_pr_sync.yml
    permissions:
      pull-requests: write
      issues: write
