name: Project

on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

jobs:
  sync:
    uses: ./.github/workflows/_project-sync.yml
    permissions:
      issues: write
      pull-requests: write
